### PR TITLE
Update response.md

### PR DESCRIPTION
**Pull request by CATOCHE**
Typo corrected: "check the" was entered twice.

### CODE REVIEW

**Comment by CATOCHE** [comment]
I was reading your documentation and I think I found a typo.

**Comment by Blackbaud-LindseyRix** [comment]
Is there a reason you closed the PR?

**Comment by CATOCHE** [comment]
I apologize. Here you go.

**Comment by Blackbaud-LindseyRix** [comment]
Thanks for your contribution! We'll get this merged in and fixed.

**Pull request merged**
